-- Seed: catalogo esercizi (circa 150 voci)
-- Popola la tabella `exercises` con esercizi pubblici in italiano,
-- suddivisi per gruppo muscolare, attrezzatura e meccanica del movimento.

-- Batch 1: petto e dorso (parte 1)
insert into exercises (name, category, muscle_group, secondary_muscles, equipment, mechanics, instructions, is_public) values
('Panca piana bilanciere', 'multiarticolare', 'petto', array['tricipiti','spalle'], 'bilanciere', 'spinta orizzontale', 'Scapole addotte e piedi ben piantati a terra. Scendi con il bilanciere al petto e spingi senza perdere l''arco lombare.', true),
('Panca inclinata bilanciere', 'multiarticolare', 'petto', array['spalle','tricipiti'], 'bilanciere', 'spinta orizzontale', 'Panca inclinata a 30-45 gradi. Porta il bilanciere alla parte alta del petto e spingi verso l''alto.', true),
('Panca declinata bilanciere', 'multiarticolare', 'petto', array['tricipiti'], 'bilanciere', 'spinta orizzontale', 'Blocca le gambe sulla panca declinata. Scendi con controllo verso la parte bassa del petto e spingi.', true),
('Panca piana manubri', 'multiarticolare', 'petto', array['tricipiti','spalle'], 'manubri', 'spinta orizzontale', 'Impugna i manubri sopra il petto e scendi ampliando leggermente la traiettoria. Spingi riavvicinando i manubri in alto.', true),
('Panca inclinata manubri', 'multiarticolare', 'petto', array['spalle','tricipiti'], 'manubri', 'spinta orizzontale', 'Su panca inclinata scendi con i gomiti a circa 45 gradi dal busto. Spingi i manubri verso l''alto senza farli sbattere.', true),
('Croci su panca piana manubri', 'isolamento', 'petto', null, 'manubri', 'isolamento', 'Braccia semitese, apri i manubri in un ampio arco fino a sentire allungare il petto. Richiudi come per abbracciare un albero.', true),
('Croci su panca inclinata manubri', 'isolamento', 'petto', null, 'manubri', 'isolamento', 'Su panca inclinata apri le braccia mantenendo i gomiti leggermente flessi. Controlla la fase di discesa.', true),
('Croci ai cavi alti', 'isolamento', 'petto', null, 'cavo', 'isolamento', 'Dai cavi alti porta le mani in basso e in avanti fino a incrociarle. Mantieni il busto leggermente inclinato.', true),
('Croci ai cavi bassi', 'isolamento', 'petto', array['spalle'], 'cavo', 'isolamento', 'Dai cavi bassi solleva le braccia in avanti e verso l''alto. Strizza il petto alto a fine corsa.', true),
('Chest press', 'multiarticolare', 'petto', array['tricipiti','spalle'], 'macchina', 'spinta orizzontale', 'Regola il sedile con le maniglie all''altezza del petto. Spingi in avanti senza bloccare i gomiti.', true),
('Chest press inclinata', 'multiarticolare', 'petto', array['spalle','tricipiti'], 'macchina', 'spinta verticale', 'Spingi le maniglie in alto e in avanti mantenendo la schiena appoggiata. Torna con controllo.', true),
('Pectoral machine', 'isolamento', 'petto', null, 'macchina', 'isolamento', 'Gomiti alla stessa altezza delle spalle. Chiudi le braccia davanti al petto e trattieni un secondo la contrazione.', true),
('Dip alle parallele', 'multiarticolare', 'petto', array['tricipiti','spalle'], 'corpo libero', 'spinta verticale', 'Busto leggermente inclinato in avanti per enfatizzare il petto. Scendi finché le spalle non arrivano sotto i gomiti.', true),
('Piegamenti sulle braccia', 'multiarticolare', 'petto', array['tricipiti','core'], 'corpo libero', 'spinta orizzontale', 'Corpo in linea dalla testa ai talloni. Scendi con il petto verso terra e spingi contraendo l''addome.', true),
('Piegamenti con piedi rialzati', 'multiarticolare', 'petto', array['spalle','tricipiti'], 'corpo libero', 'spinta orizzontale', 'Appoggia i piedi su un rialzo per enfatizzare il petto alto. Mantieni il bacino in linea con le spalle.', true),
('Pullover con manubrio', 'isolamento', 'petto', array['dorso','tricipiti'], 'manubri', 'isolamento', 'Sdraiato di traverso sulla panca, porta il manubrio dietro la testa con braccia semitese. Riporta sopra il petto espirando.', true),
('Chest press con elastici', 'multiarticolare', 'petto', array['tricipiti'], 'elastici', 'spinta orizzontale', 'Elastico dietro la schiena, spingi le mani in avanti fino a distendere le braccia. Controlla il ritorno.', true),
('Trazioni alla sbarra presa prona', 'multiarticolare', 'dorso', array['bicipiti','core'], 'corpo libero', 'trazione verticale', 'Presa poco piu larga delle spalle. Tira il petto verso la sbarra portando i gomiti verso il basso.', true),
('Trazioni presa supina', 'multiarticolare', 'dorso', array['bicipiti'], 'corpo libero', 'trazione verticale', 'Palmi rivolti verso di te, larghezza spalle. Sali fino a superare la sbarra con il mento e scendi con controllo.', true),
('Trazioni presa neutra', 'multiarticolare', 'dorso', array['bicipiti'], 'corpo libero', 'trazione verticale', 'Impugna le maniglie parallele e tira i gomiti verso i fianchi. Evita di dondolare con il corpo.', true),
('Lat machine presa larga', 'multiarticolare', 'dorso', array['bicipiti'], 'macchina', 'trazione verticale', 'Porta la barra verso la parte alta del petto aprendo il torace. Non tirare dietro la nuca.', true),
('Lat machine presa inversa', 'multiarticolare', 'dorso', array['bicipiti'], 'macchina', 'trazione verticale', 'Presa supina larghezza spalle. Tira la barra al petto tenendo i gomiti vicini al busto.', true),
('Lat machine presa neutra', 'multiarticolare', 'dorso', array['bicipiti'], 'macchina', 'trazione verticale', 'Con il triangolo o le maniglie parallele tira verso lo sterno. Petto in fuori e spalle basse.', true),
('Rematore seduto cavo', 'multiarticolare', 'dorso', array['bicipiti','spalle'], 'cavo', 'trazione orizzontale', 'Busto eretto e ginocchia morbide. Tira la maniglia all''addome portando le scapole indietro.', true),
('Rematore con bilanciere', 'multiarticolare', 'dorso', array['bicipiti','femorali'], 'bilanciere', 'trazione orizzontale', 'Busto inclinato a circa 45 gradi con schiena neutra. Tira il bilanciere verso l''ombelico e controlla la discesa.', true);

-- Batch 2: dorso (parte 2) e spalle
insert into exercises (name, category, muscle_group, secondary_muscles, equipment, mechanics, instructions, is_public) values
('Rematore con manubrio a un braccio', 'multiarticolare', 'dorso', array['bicipiti'], 'manubri', 'trazione orizzontale', 'Mano e ginocchio in appoggio sulla panca. Tira il manubrio verso il fianco senza ruotare il busto.', true),
('Rematore T-bar', 'multiarticolare', 'dorso', array['bicipiti'], 'bilanciere', 'trazione orizzontale', 'Bilanciere ancorato a terra, busto inclinato. Tira il carico verso il petto mantenendo la schiena neutra.', true),
('Rematore alla macchina', 'multiarticolare', 'dorso', array['bicipiti'], 'macchina', 'trazione orizzontale', 'Petto appoggiato al supporto. Tira le maniglie indietro concentrandoti sulla chiusura delle scapole.', true),
('Rematore inverso alla sbarra', 'multiarticolare', 'dorso', array['bicipiti','core'], 'corpo libero', 'trazione orizzontale', 'Corpo in linea sotto la sbarra bassa. Tira il petto verso la sbarra e scendi lentamente.', true),
('Rematore con elastici', 'multiarticolare', 'dorso', array['bicipiti'], 'elastici', 'trazione orizzontale', 'Elastico ancorato davanti a te. Tira le mani verso i fianchi stringendo le scapole.', true),
('Pulldown a braccia tese ai cavi', 'isolamento', 'dorso', array['tricipiti'], 'cavo', 'trazione verticale', 'Braccia quasi tese, porta la barra dal cavo alto verso le cosce. Senti lavorare il gran dorsale.', true),
('Hyperextension alla panca', 'isolamento', 'dorso', array['glutei','femorali'], 'panca', 'hinge', 'Bacino appoggiato al cuscino, scendi con il busto e risali fino alla linea del corpo. Non iperestendere la schiena.', true),
('Shrug con bilanciere', 'isolamento', 'dorso', null, 'bilanciere', 'isolamento', 'Braccia distese, solleva le spalle verso le orecchie e trattieni un secondo. Evita di ruotare le spalle.', true),
('Shrug con manubri', 'isolamento', 'dorso', null, 'manubri', 'isolamento', 'Manubri lungo i fianchi, alza le spalle in verticale con controllo. Non piegare i gomiti.', true),
('Lento avanti bilanciere', 'multiarticolare', 'spalle', array['tricipiti','core'], 'bilanciere', 'spinta verticale', 'In piedi con addome contratto, spingi il bilanciere sopra la testa fino a braccia distese. Non inarcare la zona lombare.', true),
('Lento avanti manubri seduto', 'multiarticolare', 'spalle', array['tricipiti'], 'manubri', 'spinta verticale', 'Seduto con schienale alto, spingi i manubri verso l''alto avvicinandoli a fine corsa. Scendi fino alle orecchie.', true),
('Arnold press', 'multiarticolare', 'spalle', array['tricipiti'], 'manubri', 'spinta verticale', 'Parti con i palmi verso di te e ruota i manubri durante la spinta. Movimento fluido e controllato.', true),
('Shoulder press macchina', 'multiarticolare', 'spalle', array['tricipiti'], 'macchina', 'spinta verticale', 'Schiena appoggiata e maniglie all''altezza delle spalle. Spingi in alto senza bloccare i gomiti.', true),
('Push press bilanciere', 'multiarticolare', 'spalle', array['tricipiti','quadricipiti'], 'bilanciere', 'spinta verticale', 'Piccolo piegamento di gambe e spinta esplosiva del bilanciere sopra la testa. Blocca il carico con il core attivo.', true),
('Alzate laterali manubri', 'isolamento', 'spalle', null, 'manubri', 'isolamento', 'Solleva i manubri lateralmente fino all''altezza delle spalle con i gomiti leggermente flessi. Scendi lentamente.', true),
('Alzate laterali al cavo', 'isolamento', 'spalle', null, 'cavo', 'isolamento', 'Cavo basso dietro il corpo, alza il braccio lateralmente mantenendo tensione costante. Non superare la linea della spalla.', true),
('Alzate laterali con elastici', 'isolamento', 'spalle', null, 'elastici', 'isolamento', 'Elastico sotto i piedi, solleva le braccia lateralmente fino alle spalle. Controlla il ritorno.', true),
('Alzate frontali manubri', 'isolamento', 'spalle', null, 'manubri', 'isolamento', 'Solleva i manubri davanti a te fino all''altezza degli occhi. Evita slanci con il busto.', true),
('Alzate posteriori manubri busto flesso', 'isolamento', 'spalle', array['dorso'], 'manubri', 'isolamento', 'Busto flesso in avanti, apri le braccia lateralmente puntando i gomiti verso il soffitto. Non usare slancio.', true),
('Croci inverse alla macchina', 'isolamento', 'spalle', array['dorso'], 'macchina', 'isolamento', 'Petto contro lo schienale, apri le braccia indietro fino alla linea delle spalle. Trattieni la contrazione.', true),
('Face pull ai cavi', 'isolamento', 'spalle', array['dorso'], 'cavo', 'trazione orizzontale', 'Tira la corda verso il viso separando le mani a fine corsa. Gomiti alti e spalle basse.', true),
('Tirate al mento bilanciere', 'multiarticolare', 'spalle', array['bicipiti','dorso'], 'bilanciere', 'trazione verticale', 'Presa poco piu stretta delle spalle, tira il bilanciere verso il petto guidando con i gomiti. Non superare la linea delle spalle.', true),
('Lento avanti con kettlebell', 'multiarticolare', 'spalle', array['tricipiti','core'], 'kettlebell', 'spinta verticale', 'Kettlebell in appoggio sull''avambraccio, spingi sopra la testa mantenendo il polso neutro. Core sempre attivo.', true),
('Alzate a Y su panca inclinata', 'isolamento', 'spalle', array['dorso'], 'manubri', 'isolamento', 'Petto appoggiato alla panca inclinata, solleva i manubri in diagonale formando una Y. Pollici verso l''alto.', true),
('Curl bilanciere in piedi', 'isolamento', 'bicipiti', array['core'], 'bilanciere', 'isolamento', 'Gomiti fermi ai fianchi, fletti le braccia portando il bilanciere alle spalle. Scendi in modo controllato senza dondolare.', true);

-- Batch 3: bicipiti, tricipiti e quadricipiti (parte 1)
insert into exercises (name, category, muscle_group, secondary_muscles, equipment, mechanics, instructions, is_public) values
('Curl con bilanciere EZ', 'isolamento', 'bicipiti', null, 'bilanciere', 'isolamento', 'Impugna la barra EZ sulle curve interne. Fletti i gomiti tenendoli fermi lungo i fianchi.', true),
('Curl manubri alternato', 'isolamento', 'bicipiti', null, 'manubri', 'isolamento', 'Fletti un braccio alla volta supinando il polso durante la salita. Non oscillare con il busto.', true),
('Curl a martello manubri', 'isolamento', 'bicipiti', array['tricipiti'], 'manubri', 'isolamento', 'Presa neutra con i palmi rivolti verso il corpo. Fletti i gomiti mantenendo i polsi bloccati.', true),
('Curl concentrato manubrio', 'isolamento', 'bicipiti', null, 'manubri', 'isolamento', 'Seduto, gomito appoggiato all''interno coscia. Fletti lentamente concentrandoti sul picco di contrazione.', true),
('Curl su panca inclinata', 'isolamento', 'bicipiti', null, 'manubri', 'isolamento', 'Schiena appoggiata alla panca inclinata e braccia perpendicolari a terra. Fletti mantenendo le spalle indietro.', true),
('Curl ai cavi', 'isolamento', 'bicipiti', null, 'cavo', 'isolamento', 'Dal cavo basso fletti i gomiti con tensione costante. Non far riposare il carico a fine discesa.', true),
('Curl a martello ai cavi con corda', 'isolamento', 'bicipiti', null, 'cavo', 'isolamento', 'Impugna la corda con presa neutra e fletti i gomiti. Mantieni i gomiti fermi ai fianchi.', true),
('Curl alla panca Scott', 'isolamento', 'bicipiti', null, 'panca', 'isolamento', 'Braccia appoggiate al cuscino inclinato. Fletti fino in alto e scendi senza distendere completamente i gomiti.', true),
('Curl alla macchina', 'isolamento', 'bicipiti', null, 'macchina', 'isolamento', 'Regola il sedile con le ascelle appoggiate al cuscino. Fletti e trattieni un secondo in contrazione.', true),
('Curl con elastici', 'isolamento', 'bicipiti', null, 'elastici', 'isolamento', 'Elastico sotto i piedi, fletti i gomiti mantenendoli fermi. Controlla la fase di ritorno.', true),
('French press con bilanciere EZ', 'isolamento', 'tricipiti', null, 'bilanciere', 'isolamento', 'Sdraiato sulla panca, fletti i gomiti portando la barra verso la fronte. Gomiti fermi e paralleli.', true),
('Pushdown ai cavi con corda', 'isolamento', 'tricipiti', null, 'cavo', 'isolamento', 'Gomiti bloccati ai fianchi, distendi le braccia separando la corda in basso. Torna su con controllo.', true),
('Pushdown ai cavi con barra', 'isolamento', 'tricipiti', null, 'cavo', 'isolamento', 'Spingi la barra verso il basso fino a distendere i gomiti. Spalle basse e busto stabile.', true),
('French press con manubrio seduto', 'isolamento', 'tricipiti', null, 'manubri', 'isolamento', 'Manubrio a due mani dietro la testa. Distendi le braccia verso l''alto tenendo i gomiti stretti.', true),
('Estensioni sopra la testa al cavo', 'isolamento', 'tricipiti', null, 'cavo', 'isolamento', 'Di spalle al cavo basso, distendi le braccia sopra la testa. Mantieni i gomiti vicini alle orecchie.', true),
('Estensioni con elastici sopra la testa', 'isolamento', 'tricipiti', null, 'elastici', 'isolamento', 'Elastico ancorato in basso dietro di te. Distendi le braccia sopra la testa senza aprire i gomiti.', true),
('Panca piana presa stretta', 'multiarticolare', 'tricipiti', array['petto','spalle'], 'bilanciere', 'spinta orizzontale', 'Presa alla larghezza delle spalle, gomiti vicini al busto. Scendi al petto basso e spingi in alto.', true),
('Dip tra panche', 'multiarticolare', 'tricipiti', array['petto','spalle'], 'panca', 'spinta verticale', 'Mani sul bordo della panca e gambe distese in avanti. Scendi flettendo i gomiti e risali spingendo.', true),
('Kickback con manubrio', 'isolamento', 'tricipiti', null, 'manubri', 'isolamento', 'Busto flesso e braccio parallelo al pavimento. Distendi il gomito indietro e trattieni la contrazione.', true),
('Piegamenti diamante', 'multiarticolare', 'tricipiti', array['petto','core'], 'corpo libero', 'spinta orizzontale', 'Mani unite sotto il petto a formare un rombo. Scendi con i gomiti stretti e spingi.', true),
('Estensioni tricipiti alla macchina', 'isolamento', 'tricipiti', null, 'macchina', 'isolamento', 'Gomiti appoggiati al cuscino, distendi le braccia verso il basso. Non sollevare le spalle.', true),
('Squat con bilanciere', 'multiarticolare', 'quadricipiti', array['glutei','femorali','core'], 'bilanciere', 'squat', 'Bilanciere sui trapezi e piedi larghezza spalle. Scendi sotto il parallelo mantenendo la schiena neutra e spingi con tutto il piede.', true),
('Front squat bilanciere', 'multiarticolare', 'quadricipiti', array['glutei','core'], 'bilanciere', 'squat', 'Bilanciere in appoggio sulle spalle anteriori con gomiti alti. Scendi tenendo il busto il piu verticale possibile.', true),
('Goblet squat con kettlebell', 'multiarticolare', 'quadricipiti', array['glutei','core'], 'kettlebell', 'squat', 'Kettlebell al petto, scendi tra le ginocchia mantenendo i talloni a terra. Risali spingendo il pavimento.', true),
('Leg press', 'multiarticolare', 'quadricipiti', array['glutei','femorali'], 'macchina', 'squat', 'Piedi al centro della pedana, scendi finché le ginocchia raggiungono circa 90 gradi. Non staccare il bacino dal sedile.', true);

-- Batch 4: quadricipiti (parte 2), femorali e glutei
insert into exercises (name, category, muscle_group, secondary_muscles, equipment, mechanics, instructions, is_public) values
('Leg extension', 'isolamento', 'quadricipiti', null, 'macchina', 'isolamento', 'Regola il rullo sopra le caviglie. Distendi le gambe e trattieni un secondo in massima contrazione.', true),
('Hack squat', 'multiarticolare', 'quadricipiti', array['glutei'], 'macchina', 'squat', 'Spalle sotto i cuscini e piedi avanti sulla pedana. Scendi con controllo e risali senza bloccare le ginocchia.', true),
('Affondi con manubri', 'multiarticolare', 'quadricipiti', array['glutei','femorali'], 'manubri', 'lunge', 'Passo in avanti e discesa verticale del bacino. Il ginocchio posteriore sfiora terra, poi spingi per tornare.', true),
('Affondi camminati con bilanciere', 'multiarticolare', 'quadricipiti', array['glutei','core'], 'bilanciere', 'lunge', 'Bilanciere sulle spalle, avanza alternando le gambe con passi ampi. Busto eretto e core attivo.', true),
('Affondi inversi con bilanciere', 'multiarticolare', 'quadricipiti', array['glutei','femorali'], 'bilanciere', 'lunge', 'Passo indietro e discesa controllata del ginocchio. Spingi con la gamba avanti per risalire.', true),
('Squat bulgaro con manubri', 'multiarticolare', 'quadricipiti', array['glutei','femorali'], 'manubri', 'lunge', 'Piede posteriore in appoggio sulla panca. Scendi in verticale con il busto leggermente inclinato in avanti.', true),
('Step-up su panca con manubri', 'multiarticolare', 'quadricipiti', array['glutei'], 'manubri', 'lunge', 'Sali sulla panca spingendo con la gamba in appoggio, senza darti slancio con quella a terra. Scendi con controllo.', true),
('Squat a corpo libero', 'multiarticolare', 'quadricipiti', array['glutei','core'], 'corpo libero', 'squat', 'Piedi larghezza spalle e braccia avanti per bilanciare. Scendi sotto il parallelo mantenendo i talloni a terra.', true),
('Pistol squat', 'multiarticolare', 'quadricipiti', array['glutei','core'], 'corpo libero', 'squat', 'Squat su una gamba con l''altra distesa in avanti. Scendi lentamente mantenendo l''equilibrio.', true),
('Sissy squat', 'isolamento', 'quadricipiti', null, 'corpo libero', 'squat', 'In piedi sugli avampiedi, piega le ginocchia in avanti inclinando il busto indietro in linea con le cosce. Movimento lento.', true),
('Sedia al muro', 'isolamento', 'quadricipiti', array['glutei'], 'corpo libero', 'squat', 'Schiena contro il muro e cosce parallele al pavimento. Mantieni la posizione respirando in modo regolare.', true),
('Leg curl sdraiato', 'isolamento', 'femorali', null, 'macchina', 'isolamento', 'Rullo sopra i talloni, fletti le ginocchia portando i talloni ai glutei. Non sollevare il bacino dal cuscino.', true),
('Leg curl seduto', 'isolamento', 'femorali', null, 'macchina', 'isolamento', 'Regola i cuscini su cosce e caviglie. Fletti le ginocchia verso il basso e torna con controllo.', true),
('Leg curl in piedi al cavo', 'isolamento', 'femorali', null, 'cavo', 'isolamento', 'Cavigliera collegata al cavo basso. Fletti il ginocchio portando il tallone al gluteo senza muovere il bacino.', true),
('Leg curl con elastico', 'isolamento', 'femorali', null, 'elastici', 'isolamento', 'Elastico ancorato in basso e fissato alla caviglia. Fletti il ginocchio con movimento lento e controllato.', true),
('Stacco rumeno con bilanciere', 'multiarticolare', 'femorali', array['glutei','dorso'], 'bilanciere', 'hinge', 'Ginocchia poco flesse, spingi il bacino indietro facendo scorrere il bilanciere lungo le gambe. Risali contraendo i glutei.', true),
('Romanian deadlift manubri', 'multiarticolare', 'femorali', array['glutei','dorso'], 'manubri', 'hinge', 'Manubri davanti alle cosce, fletti il bacino indietro con schiena neutra. Senti l''allungamento dei femorali e risali.', true),
('Stacco a gambe tese bilanciere', 'multiarticolare', 'femorali', array['glutei','dorso'], 'bilanciere', 'hinge', 'Gambe quasi distese, scendi con il busto mantenendo la schiena in posizione neutra. Non arrotondare la zona lombare.', true),
('Good morning con bilanciere', 'multiarticolare', 'femorali', array['glutei','dorso'], 'bilanciere', 'hinge', 'Bilanciere sui trapezi, fletti il busto in avanti spingendo il bacino indietro. Risali contraendo glutei e femorali.', true),
('Nordic curl', 'isolamento', 'femorali', array['glutei'], 'corpo libero', 'isolamento', 'Caviglie bloccate, scendi in avanti frenando con i femorali il piu a lungo possibile. Aiutati con le mani a risalire.', true),
('Sliding leg curl', 'isolamento', 'femorali', array['glutei','core'], 'corpo libero', 'isolamento', 'Supino con talloni su dischi scivolosi, solleva il bacino e fletti le ginocchia facendo scorrere i piedi verso i glutei.', true),
('Hip thrust con bilanciere', 'multiarticolare', 'glutei', array['femorali','core'], 'bilanciere', 'hinge', 'Schiena alta appoggiata alla panca e bilanciere sul bacino. Spingi il bacino in alto fino alla linea del corpo e strizza i glutei.', true),
('Ponte glutei a corpo libero', 'isolamento', 'glutei', array['femorali'], 'corpo libero', 'hinge', 'Supino con ginocchia flesse, solleva il bacino contraendo i glutei. Trattieni un secondo in alto.', true),
('Hip thrust a una gamba', 'isolamento', 'glutei', array['femorali','core'], 'corpo libero', 'hinge', 'Spalle sulla panca e una gamba sollevata. Spingi il bacino in alto con la gamba in appoggio.', true),
('Swing con kettlebell', 'multiarticolare', 'glutei', array['femorali','core','dorso'], 'kettlebell', 'hinge', 'Movimento esplosivo di anca: spingi il bacino indietro e poi in avanti facendo salire il kettlebell al petto. Braccia rilassate.', true);

-- Batch 5: glutei (parte 2), polpacci e core
insert into exercises (name, category, muscle_group, secondary_muscles, equipment, mechanics, instructions, is_public) values
('Slanci posteriori al cavo', 'isolamento', 'glutei', array['femorali'], 'cavo', 'isolamento', 'Cavigliera al cavo basso, spingi la gamba indietro contraendo il gluteo. Busto fermo e core attivo.', true),
('Slanci posteriori a quattro appoggi', 'isolamento', 'glutei', array['femorali'], 'corpo libero', 'isolamento', 'In quadrupedia, spingi il tallone verso il soffitto con ginocchio flesso. Non inarcare la zona lombare.', true),
('Abduzioni alla macchina', 'isolamento', 'glutei', null, 'macchina', 'isolamento', 'Seduto con schiena appoggiata, apri le ginocchia contro la resistenza. Torna lentamente senza far cadere il carico.', true),
('Camminata laterale con elastico', 'isolamento', 'glutei', array['quadricipiti'], 'elastici', 'isolamento', 'Elastico sopra le ginocchia, esegui passi laterali in leggero squat. Mantieni tensione costante sull''elastico.', true),
('Sumo squat con manubrio', 'multiarticolare', 'glutei', array['quadricipiti','femorali'], 'manubri', 'squat', 'Piedi larghi e punte in fuori, manubrio tra le gambe. Scendi verticale e risali contraendo i glutei.', true),
('Stacco sumo con bilanciere', 'multiarticolare', 'glutei', array['quadricipiti','femorali','dorso'], 'bilanciere', 'hinge', 'Piedi molto larghi e presa interna alle ginocchia. Spingi il pavimento con le gambe mantenendo il busto verticale.', true),
('Calf raise in piedi', 'isolamento', 'polpacci', null, 'macchina', 'isolamento', 'Avampiedi sul rialzo, scendi in massimo allungamento e sali sulle punte. Fermati un secondo in alto.', true),
('Calf raise seduto', 'isolamento', 'polpacci', null, 'macchina', 'isolamento', 'Ginocchia sotto i cuscini, solleva i talloni con movimento completo. Lavora il soleo con ritmo lento.', true),
('Calf raise alla leg press', 'isolamento', 'polpacci', null, 'macchina', 'isolamento', 'Avampiedi sul bordo basso della pedana. Spingi con le punte estendendo le caviglie a fondo.', true),
('Calf raise in piedi con manubrio', 'isolamento', 'polpacci', null, 'manubri', 'isolamento', 'Manubrio in una mano e avampiede su un gradino. Sali sulla punta di un piede alla volta con corsa completa.', true),
('Calf raise a corpo libero su gradino', 'isolamento', 'polpacci', null, 'corpo libero', 'isolamento', 'Avampiedi sul gradino e talloni liberi. Scendi sotto il parallelo e sali sulle punte lentamente.', true),
('Calf raise con bilanciere', 'isolamento', 'polpacci', null, 'bilanciere', 'isolamento', 'Bilanciere sulle spalle come nello squat. Sollevati sulle punte mantenendo l''equilibrio e scendi piano.', true),
('Plank', 'core', 'core', array['spalle','glutei'], 'corpo libero', 'isolamento', 'Gomiti sotto le spalle e corpo in linea. Contrai addome e glutei senza far cadere il bacino.', true),
('Plank laterale', 'core', 'core', array['spalle'], 'corpo libero', 'isolamento', 'Appoggio su un gomito e sul bordo del piede. Bacino alto e corpo in linea, respira regolarmente.', true),
('Plank con tocco spalle', 'core', 'core', array['spalle'], 'corpo libero', 'isolamento', 'In plank su mani, tocca la spalla opposta con una mano alla volta. Bacino fermo senza oscillazioni.', true),
('Crunch a terra', 'core', 'core', null, 'corpo libero', 'isolamento', 'Ginocchia flesse e mani alle tempie. Solleva le scapole da terra espirando, senza tirare il collo.', true),
('Crunch inverso', 'core', 'core', null, 'corpo libero', 'isolamento', 'Supino con gambe flesse, porta le ginocchia al petto sollevando il bacino. Scendi senza inarcare la schiena.', true),
('Crunch ai cavi in ginocchio', 'core', 'core', null, 'cavo', 'isolamento', 'In ginocchio con la corda dietro la nuca. Fletti il busto verso il basso arrotondando la schiena.', true),
('Sollevamento gambe alla sbarra', 'core', 'core', array['dorso'], 'corpo libero', 'isolamento', 'Appeso alla sbarra, solleva le gambe distese fino all''orizzontale. Evita di dondolare tra le ripetizioni.', true),
('Russian twist', 'core', 'core', null, 'corpo libero', 'isolamento', 'Seduto con busto inclinato indietro e piedi sollevati. Ruota il busto da un lato all''altro con controllo.', true),
('Rollout con ruota', 'core', 'core', array['spalle','dorso'], 'corpo libero', 'isolamento', 'In ginocchio, fai rotolare la ruota in avanti mantenendo l''addome contratto. Non lasciar cedere la zona lombare.', true),
('Dead bug', 'core', 'core', null, 'corpo libero', 'isolamento', 'Supino con braccia e ginocchia in alto. Distendi lentamente braccio e gamba opposti tenendo la schiena a terra.', true),
('Bird dog', 'core', 'core', array['glutei','dorso'], 'corpo libero', 'isolamento', 'In quadrupedia distendi braccio e gamba opposti mantenendo il bacino stabile. Torna e cambia lato.', true),
('Hollow hold', 'core', 'core', null, 'corpo libero', 'isolamento', 'Supino con braccia e gambe sollevate e zona lombare premuta a terra. Mantieni la posizione respirando.', true),
('Pallof press ai cavi', 'core', 'core', array['spalle'], 'cavo', 'isolamento', 'Di fianco al cavo, distendi le braccia davanti al petto resistendo alla rotazione. Bacino e spalle fermi.', true);

-- Batch 6: core (parte 2), full body, cardio e mobilità
insert into exercises (name, category, muscle_group, secondary_muscles, equipment, mechanics, instructions, is_public) values
('Sit-up', 'core', 'core', null, 'corpo libero', 'isolamento', 'Ginocchia flesse, solleva tutto il busto fino alla posizione seduta. Scendi vertebra dopo vertebra.', true),
('Stacco da terra', 'multiarticolare', 'full body', array['dorso','glutei','femorali','core'], 'bilanciere', 'hinge', 'Bilanciere sopra il mesopiede e schiena neutra. Spingi il pavimento con le gambe e distendi il bacino fino alla posizione eretta.', true),
('Girata e spinta con bilanciere', 'multiarticolare', 'full body', array['spalle','glutei','core'], 'bilanciere', 'spinta verticale', 'Porta il bilanciere alle spalle con una girata esplosiva, poi spingilo sopra la testa. Tecnica prima del carico.', true),
('Thruster con manubri', 'multiarticolare', 'full body', array['quadricipiti','spalle','core'], 'manubri', 'spinta verticale', 'Front squat con manubri alle spalle e spinta sopra la testa in un unico movimento fluido. Sfrutta la spinta delle gambe.', true),
('Snatch con manubrio', 'multiarticolare', 'full body', array['spalle','glutei','core'], 'manubri', 'hinge', 'Porta il manubrio da terra sopra la testa in un solo movimento esplosivo. Estendi bacino e ginocchia con forza.', true),
('Farmer walk con kettlebell', 'multiarticolare', 'full body', array['core','dorso','polpacci'], 'kettlebell', 'carry', 'Cammina con un kettlebell pesante per mano. Spalle basse, busto eretto e passi corti e stabili.', true),
('Turkish get-up con kettlebell', 'multiarticolare', 'full body', array['core','spalle','glutei'], 'kettlebell', 'carry', 'Da sdraiato ad in piedi mantenendo il kettlebell sopra la testa. Esegui ogni passaggio lentamente guardando il carico.', true),
('Corsa su tapis roulant', 'cardio', 'cardio', null, 'macchina', null, 'Corri a ritmo costante mantenendo una postura eretta. Aumenta gradualmente velocita o pendenza.', true),
('Camminata in salita su tapis roulant', 'cardio', 'cardio', null, 'macchina', null, 'Imposta una pendenza del 8-12 percento e cammina a passo sostenuto. Evita di aggrapparti ai manubri.', true),
('Cyclette', 'cardio', 'cardio', null, 'macchina', null, 'Regola la sella all''altezza del bacino. Pedala a cadenza regolare mantenendo le spalle rilassate.', true),
('Ellittica', 'cardio', 'cardio', null, 'macchina', null, 'Movimento fluido spingendo con gambe e braccia. Mantieni il busto eretto senza appoggiarti alle maniglie.', true),
('Vogatore', 'cardio', 'cardio', array['dorso','quadricipiti'], 'macchina', null, 'Sequenza gambe-busto-braccia in tirata e inversa in ritorno. Schiena neutra per tutta la vogata.', true),
('Salto della corda', 'cardio', 'cardio', array['polpacci'], 'corpo libero', null, 'Salta basso sugli avampiedi facendo girare la corda con i polsi. Ritmo costante e ginocchia morbide.', true),
('Burpee', 'cardio', 'full body', array['petto','quadricipiti','core'], 'corpo libero', null, 'Piegamento a terra, salto dei piedi verso le mani e balzo verticale. Mantieni un ritmo sostenibile.', true),
('Mountain climber', 'cardio', 'core', array['spalle','quadricipiti'], 'corpo libero', null, 'In posizione di plank su mani, porta le ginocchia al petto alternandole rapidamente. Bacino basso e stabile.', true),
('Jumping jack', 'cardio', 'cardio', array['polpacci','spalle'], 'corpo libero', null, 'Salta aprendo gambe e braccia contemporaneamente, poi richiudi. Atterra morbido sugli avampiedi.', true),
('Skip a ginocchia alte', 'cardio', 'cardio', array['core','quadricipiti'], 'corpo libero', null, 'Corri sul posto portando le ginocchia all''altezza del bacino. Braccia coordinate e busto eretto.', true),
('Gatto-cammello', 'mobilità', 'core', array['dorso'], 'corpo libero', null, 'In quadrupedia alterna la flessione e l''estensione della colonna con il respiro. Movimento lento e completo.', true),
('Estensione toracica a terra', 'mobilità', 'dorso', null, 'corpo libero', null, 'Supporto sotto la parte alta della schiena e mani dietro la nuca. Estendi il tratto toracico senza inarcare la zona lombare.', true),
('Dislocazioni delle spalle con bastone', 'mobilità', 'spalle', array['petto'], 'corpo libero', null, 'Impugna un bastone con presa larga e portalo da davanti a dietro con braccia tese. Riduci la presa nel tempo.', true),
('Affondo con rotazione del busto', 'mobilità', 'full body', array['glutei','core'], 'corpo libero', null, 'Affondo profondo con mano a terra e rotazione del busto verso il cielo. Alterna i lati con calma.', true),
('Allungamento dei flessori dell''anca in affondo', 'mobilità', 'quadricipiti', array['glutei'], 'corpo libero', null, 'In affondo con ginocchio a terra, spingi il bacino in avanti mantenendo il busto eretto. Respira e mantieni 30 secondi.', true),
('Stretching dei femorali da sdraiato', 'mobilità', 'femorali', null, 'corpo libero', null, 'Supino, porta una gamba tesa verso di te aiutandoti con le mani o un elastico. Mantieni l''altra gamba a terra.', true),
('Stretching del piriforme da sdraiato', 'mobilità', 'glutei', null, 'corpo libero', null, 'Supino, incrocia una caviglia sul ginocchio opposto e tira la coscia verso il petto. Mantieni senza molleggiare.', true),
('Stretch delle anche 90/90', 'mobilità', 'glutei', array['quadricipiti'], 'corpo libero', null, 'Seduto con entrambe le gambe piegate a 90 gradi. Inclina il busto in avanti sulla gamba anteriore mantenendo la schiena lunga.', true);
